"""EDA endpoint: serve the precomputed exploratory-analysis summary."""
from __future__ import annotations

from fastapi import APIRouter, HTTPException

from src.utils import config
from src.utils.helpers import read_json

router = APIRouter(prefix="/api", tags=["eda"])


@router.get("/eda")
def get_eda() -> dict:
    """Return the EDA summary (generated by notebooks/eda.py)."""
    data = read_json(config.EDA_SUMMARY_PATH)
    if data is None:
        raise HTTPException(
            status_code=503,
            detail="EDA summary not found. Run `python notebooks/eda.py`.",
        )
    return data
