"""Rules endpoint: serve the derived business-readable credit rules."""
from __future__ import annotations

from fastapi import APIRouter, HTTPException

from src.utils import config
from src.utils.helpers import read_json

router = APIRouter(prefix="/api", tags=["rules"])


@router.get("/rules")
def get_rules() -> dict:
    """Return derived IF/THEN rules (generated by src.rules.derive_rules)."""
    data = read_json(config.RULES_PATH)
    if data is None:
        raise HTTPException(
            status_code=503,
            detail="Rules not found. Run `python -m src.rules.derive_rules`.",
        )
    return data
